# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
additional_authors_raw: Kaitlyn Kobayashi
author_email: bhklab.katyscott@gmail.com
author_full_name: Katy Scott
github_username: strixy16
has_additional_authors: true
project_description: Preprocessing of datasets for use in the AAuRA Benchmarking tool.
project_name: AAuRA Benchmark Preprocessing
project_slug: aaura-bench-preprocess
publish_to_github: true
python_version: '3.11'
repo_location: bhklab
