from pathlib import Path
import pandas as pd
import logging
import numpy as np
logger = logging.getLogger(__name__)


def make_edges_df(mit_index: pd.DataFrame | Path,
                  image_modality: str,
                  mask_modality: str) -> pd.DataFrame:
    """Create rows for matching images and masks from an imgtools autopipeline dataset index file. Each image may have multiple masks, so a row is created for each combination.
    
    Parameters
    ----------
    mit_index : pd.DataFrame | Path
        DataFrame or Path to csv file containing the index data generated by running imgtools autopipeline. Can be from the index.csv or index-simple.csv. Must contain:

        * 'filepath'
        * 'PatientID'
        * 'SampleNumber'
        * 'Modality'
        * 'ImageID'
        * 'SeriesInstanceUID'
        * 'ReferencedSeriesUID'
    image_modality : str
        Modality to filter the index by to get image rows (e.g. CT, MR)
    mask_modality : str
        Modality to filter the index by to get mask rows (e.g. RTSTRUCT, SEG)
            
    Returns
    -------
    edges_df : pd.DataFrame
        DataFrame where each row contains metadata for an image and mask pair. 
    """
    if isinstance(mit_index, Path):
        # Check that the correct file name has been passed
        if not (mit_index.name.endswith("index.csv") or mit_index.name.endswith("index-simple.csv")):
            message = "Expected imgtools autopipeline index file ending in 'index.csv' or 'index-simple.csv'."
            logger.error(message)
            raise ValueError(message)
        # Load the file into a pandas DataFrame
        mit_index = pd.read_csv(mit_index)
    
    # Get the image rows and mask rows from the MIT index and merge based on 
    #   - mask's ReferencedSeriesUID == image's SeriesInstanceUID
    #   - Matching SampleNumber
    #   - Matching PatientID
    edges_df = mit_index[mit_index.Modality == image_modality].merge(
        mit_index[mit_index.Modality == mask_modality],
        left_on=['SeriesInstanceUID', 'SampleNumber', 'PatientID'],
        right_on=['ReferencedSeriesUID', 'SampleNumber', 'PatientID'],
        suffixes=('_image', '_mask')
    )
        
    return edges_df


def insert_SampleID(dataset_index:pd.DataFrame) -> pd.DataFrame:
    """Combine the PatientID and SampleNumber columns in an index to generate a SampleID
       SampleNumber is padded with 0s to make a length of four.
    """
    if "SampleID" in dataset_index.columns:
        logger.info("SampleID column already exists in this dataset_index.")
        return dataset_index
    
    if "PatientID" not in dataset_index.columns:
        message = "PatientID column is missing in this dataset_index. Cannot make SampleID."
        logger.error(message)
        raise KeyError(message)
    
    if "SampleNumber" not in dataset_index.columns:
        message = "SampleNumber column is missing in this dataset_index. Cannot make SampleID."
        logger.error(message)
        raise KeyError(message)

    sample_id_series = dataset_index['PatientID'].astype(str) + "_" + dataset_index['SampleNumber'].astype(str).str.zfill(4)
    dataset_index.insert(0, "SampleID", sample_id_series)

    return dataset_index
